### ISSUE TITLE
Please remove dependency on SharpZipLib its GPL

### ISSUE THREAD

**Issue by AnderssonPeter** [ExcelDataReader/ExcelDataReader#56] opened 2015-02-27 08:54 UTC
Please change SharpZipLib to something with a less restrictive license like DotNetZip or 7ZIP SDK for C#.

**Comment by Ian1971** [comment] 2015-02-27 11:22
The version in the develop branch  (at least for the .net 4.5 version
anyway) does not use SharpZipLib but the .net framework 4.5 built in zip
feature.

On Fri, Feb 27, 2015 at 8:54 AM, Peter <notifications@github.com> wrote:

> Please change SharpZipLib to something with a less restrictive license
> like DotNetZip or 7ZIP SDK for C#.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/56>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as Release Consulting Ltd.
Number: 06323661 VAT: 919231428

**Comment by bridsonc** [comment] 2015-03-14 12:37
I keep getting an error with ExcelReaderFactory.CreateOpenXmlReader()

I think it's related to SharpZipLib.

"A first chance exception of type 'System.IO.FileNotFoundException' occurred in Excel.dll

Additional information: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The system cannot find the file specified."

I am using Visual Studio 2013 and .NET Framework 4.5

**Comment by bridsonc** [comment] 2015-03-14 12:38
I also used to Nu-get to try to Install-Package SharpZipLib

'SharpZipLib 0.86.0' already installed.
PERA already has a reference to 'SharpZipLib 0.86.0'.

**Comment by Ian1971** [comment] 2015-03-14 14:41
If you build the version in develop branch that has no dependency on
sharpziplib for. Net 4.5

**Comment by bridsonc** [comment] 2015-03-14 14:59
@Ian1971 Not sure how to build it.  I cloned the develop branch but IDK where to go from there.

**Comment by Ian1971** [comment] 2015-03-14 15:11
Open sln file.  Exceldatareader.sln I think.  Build it in release mode.
Then copy the dlls  from bin folder to your project.

**Comment by bridsonc** [comment] 2015-03-14 15:12
the dll's from Excel/bin/Debug?

**Comment by Ian1971** [comment] 2015-03-14 15:21
Yes.  Or bin/release depending on if you built debug or release mode.

**Comment by JeffB42** [comment] 2015-05-13 14:16
@Ian1971 said... "If you build the version in develop branch that has no dependency on
sharpziplib for. Net 4.5"

I just grabbed the latest snapshot from the develop branch.  
ExcelDataReader /Excel/Core/ZipWorker.cs (https://github.com/ExcelDataReader/ExcelDataReader/blob/develop/Excel/Core/ZipWorker.cs) still has a dependency on ICSharpCode.SharpZipLib.Zip and ZipEntry.

Jeff

**Comment by Ian1971** [comment] 2015-05-13 14:21
That code shouldn't be used by the 4.5 version  only. Net 2 as 4.5 should
be using the native zip support.

**Comment by JeffB42** [comment] 2015-05-13 15:35
> That code shouldn't be used by the 4.5 version

That's what I'm seeing, but the issue is that I need to use the .NET 4.0 version, which apparently relies on SharpZipLib.

**Comment by Ian1971** [comment] 2015-05-13 15:43
ah yes..,.4.0 does. I think the native zip came with 4.5

On Wed, May 13, 2015 at 4:35 PM, JeffB42 <notifications@github.com> wrote:

> That code shouldn't be used by the 4.5 version
>
> That's what I'm seeing, but the issue is that I need to use the .NET 4.0
> version, which apparently relies on SharpZipLib.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/56#issuecomment-101717854>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by wtaniguchi** [comment] 2015-05-26 18:07
I got the 2.0 code base (Excel.csproj) working (at least passing all tests :)) with .NET 4.5's System.IO.Compression libraries. Of course I had to change targets to 4.5, but it works better for me because I have to deploy less libraries.

If the original request is still pending, I believe I can manage to get it working with DotNetZip or SevenZipSharp.

Cheers,

**Comment by JeffB42** [comment] 2015-05-27 14:43
That won't help my situation - due to infrastructure limitations here, I can't deploy .NET 4.5 binaries to production - I'm limited to .NET 4.0.

**Comment by wtaniguchi** [comment] 2015-05-27 14:53
@JeffB42 Yeah, I figured that out.

However, System.IO.Packaging.ZipPackage would do pretty much the same thing in this scenario, and it is available in NET 4.0.

**Comment by jgschwend** [comment] 2017-04-11 09:32
Hi there,
I currently using ExcelDataReader 2.1.2.1 included into my project (.NET 4.5.2) using Nuget.
Is there already new release, without dependencies on SharpZipLib?
I would like to get rid of this dependency, since it's very old.

Regards,
Jonas

**Comment by andersnm** [comment] 2017-06-26 11:34
Technically, SharpZipLib is GPL with an exception permitting use of the library in commercial closed-source applications. See the License section here: https://icsharpcode.github.io/SharpZipLib/

Additionally, latest prealpha NuGets only fall back to SharpZipLib on net20 targets. net45 and netstandard uses System.IO.Compression.

Is this sufficient to close this issue, or is there still need for a completely GPL-free alternative on net20?

**Closed** 2017-07-21 20:12 UTC
