### ISSUE TITLE
Can i read a image from a excel cell?

### ISSUE THREAD

**Issue by akashpandey1310** [ExcelDataReader/ExcelDataReader#513] opened 2021-03-09 08:34 UTC
I am unable to read images from an excel, used numerous no. of excel sheets but still i am unable to find any solution to this is this library can read a image as well from an excel cell and give it to me in any format like base64 or any string?

**Comment by appel1** [comment] 2022-12-03 10:40
Duplicate of #202

**Closed by appel1** 2022-12-03 10:40 UTC
Labels: duplicate
