### ISSUE TITLE
XLS file exception on date time conversion.

### ISSUE THREAD

**Issue by EricGitHub74** [ExcelDataReader/ExcelDataReader#65] opened 2015-04-23 14:55 UTC
Hello, 

I've a XLS file which raises a "Object reference not set to an instance of an object" exception when I try to call the method AsDataSet(true) from the binary reader.
The stack trace shows the issue in the ExcelDataReader code (ExcelBinaryReader.cs line 894). It seems the method does not handle if the value object is null.

Could you fix this please?

Many thanks.

**Comment by Ian1971** [comment] 2015-04-23 15:22
It can certainly be added to the list, but a fix isn't going to be
forthcoming very soon as I am too busy on project work at the moment. If
you are so inclined you could fork it, fix it and submit a pull request.
That would be appreciated.

On Thu, Apr 23, 2015 at 3:55 PM, EricGitHub74 <notifications@github.com>
wrote:

> Hello,
>
> I've a XLS file which raises a "Object reference not set to an instance of
> an object" exception when I try to call the method AsDataSet(true).
> The stack trace shows the issue in the ExcelDataReader code
> (ExcelBinaryReader.cs line 894). It seems the method does not handle if the
> value object is null.
>
> Could you fix this please?
>
> Many thanks.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/65>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by andersnm** [comment] 2017-06-11 09:54
Duplicate of #3 and #70

**Closed by andersnm** 2017-06-11 09:54 UTC
