### ISSUE TITLE
read xls ,a few character appear as gibberish

### ISSUE THREAD

**Issue by johnfwtest** [ExcelDataReader/ExcelDataReader#162] opened 2016-09-27 07:24 UTC
i save a  file as xls  that use the Excel 2016. the conent just like this.
![image](https://cloud.githubusercontent.com/assets/19530162/18863359/7bb2c36a-84c3-11e6-8fa4-c745771b5f1d.png)
the case file :https://github.com/johnfwtest/TestFiles/blob/master/test1.xls
i use the ExcelBinaryReader to read it, because the file type is xls. i can got a datatable. but a few character appear as gibberish, even got a null string.
I use the "TestApp.exe" to read it.,and i got the same result.
![image](https://cloud.githubusercontent.com/assets/19530162/18864020/c896261a-84c6-11e6-884c-38c751c2f81a.png)

**Comment by wizardgsz** [comment] 2016-09-27 07:52
Try changing typeface please.

![typeface](https://cloud.githubusercontent.com/assets/8364153/18864781/1fd4fc82-8498-11e6-94ff-0a843121ae88.png)

**Comment by johnfwtest** [comment] 2016-09-27 08:29
![image](https://cloud.githubusercontent.com/assets/19530162/18865329/4b348f2a-84cd-11e6-91e6-b98e9dc0ee28.png)
i try change the font to Arial,等线 and Microsoft YaHei UI, but no change in result.

**Comment by appel1** [comment] 2016-10-12 07:33
Looks like a duplicate of #145.

**Closed** 2016-10-12 07:54 UTC

**Comment by johnfwtest** [comment] 2016-10-12 08:00
just as @appel1 said ,  why that line was commented???
