### ISSUE TITLE
Getting NullReferenceException

### ISSUE THREAD

**Issue by md-elyas** [ExcelDataReader/ExcelDataReader#86] opened 2015-10-07 21:27 UTC
I'm getting this error:

NullReferenceException: Object reference not set to an instance of an object
System.Data.Common.DoubleDataContainer.DoCopyValue (System.Data.Common.DataContainer from, Int32 from_index, Int32 to_index)
System.Data.Common.DataContainer.CopyValue (System.Data.Common.DataContainer from, Int32 from_index, Int32 to_index)
System.Data.Common.RecordCache.CopyRecord (System.Data.DataTable fromTable, Int32 fromRecordIndex, Int32 toRecordIndex)

when trying to use reader.AsDataSet();

Would appreciate any insight into this.

**Comment by wizardgsz** [comment] 2015-10-07 21:44
I think you should (must) provide an example to replicate this issue :)
Xamarin uses the library?
https://bugzilla.xamarin.com/show_bug.cgi?id=32795

**Comment by md-elyas** [comment] 2015-10-08 04:05
Sorry about that, pretty new to github :x

Here is the code that I'm testing with:


    public static TestReader instance
    {
        get
        {
            if(_instance == null)
            {
                _instance = new TestReader();
            }
            return _instance;
        }
    }

    private string filePath = Application.dataPath + "/monster_tug.xlsx";

    public void TestRead()
    {

        FileStream stream = File.Open(filePath, FileMode.Open, FileAccess.Read);

        IExcelDataReader reader = ExcelReaderFactory.CreateOpenXmlReader(stream);

        Debug.Log(reader.Name);

        reader.IsFirstRowAsColumnNames = true;

        DataSet newSet = reader.AsDataSet();

        reader.Close();
    }


The error pops up when I try to use the AsDataSet() function.

**Comment by edgarrc** [comment] 2015-10-16 19:41
Looks like the same problem reported here:

https://bugzilla.xamarin.com/show_bug.cgi?id=32795

**Comment by edgarrc** [comment] 2015-10-16 20:54
Just as a workaround I changed the excelReader to:

excelReader.IsFirstRowAsColumnNames = false;

And changed the loop to row 1 to .Rows.Count - 1 (instead of 0 to .Rows.Count - 1). So, on my code, I'm just ignoring the first row.

And it is working fine on mono/linux as well.

**Comment by andersnm** [comment] 2017-07-02 11:08
This is a duplicate of #73 and #30. Not sure if this was fixed in Mono since then. 

Another workaround in the latest develop branch is to set `ExcelDataSetConfiguration.UseColumnDataType = false` when calling AsDataSet()

**Closed by andersnm** 2017-07-02 11:08 UTC
