### ISSUE TITLE
Importing XLSX file with AsDataSet() without parsing it into DateTime format.

### ISSUE THREAD

**Issue by sawaisaslam** [ExcelDataReader/ExcelDataReader#95] opened 2015-12-21 12:07 UTC
I have some .xlsx files with a column that contains date in D/M/Y format. I am reading this file with

ExcelReaderFactory.CreateOpenXmlReader(stream);

Now I want to get my date column in string format in my data table. I have tried following:

DataSet result = excelReader.AsDataSet();
DataSet result = excelReader.AsDataSet(true);

By both ways it is returning me the data e.g. 7/11/2015 as 7/11/2015 12:00:00AM {System.DateTime}. How can I parse this date into {System.String} object?

**Comment by weitzhandler** [comment] 2015-12-23 09:20
Have you tried passing `false` as the constructor argument?

**Comment by bsweiss1** [comment] 2016-02-12 17:49
We are having the same problem here.  We are able to preserve the same date formatting that is in the XLS file columns but are not able to keep the same date formats that are in XLSX files.  Are we missing something here?

**Comment by andersnm** [comment] 2017-06-29 12:11
This is effectively a duplicate of #90 "Support ConvertOaDate parameter in ExcelOpenXmlReader"

**Closed by andersnm** 2017-06-29 12:11 UTC

**Comment by szymon954-code** [comment] 2021-04-26 08:52
Check the project has a installed the `ExcelDataReader.DataSet` package
