### ISSUE TITLE
Suggestion for adding reading named range 

### ISSUE THREAD

**Issue by Andreybonfi** [ExcelDataReader/ExcelDataReader#655] opened 2023-10-01 16:37 UTC
Hello, I would like to propose an implementation of these methods so that they can return named ranges.
All named ranges are stored in the book file, so this will not affect the speed. I have already implemented xlsx reader. And, if you think this is interesting, then I will implement a binary one.

Tables declared inside a sheet are named range; adding such functions can simplify the search for data boundaries.

```CS
        public string GetName(int i) 
        {
            if (RowCells == null)
                throw new InvalidOperationException("No data exists for the row/column.");
            
            var rowIndex = _rowIterator.Current.RowIndex;

            var namedRanges = NamedRanges
                .Where(x =>
                    (x.FromRow == rowIndex && x.FromColumn == i && x.ToRow == null)
                    ||
                    (rowIndex >= x.FromRow && rowIndex <= x.ToColumn && i >= x.FromColumn && i <= x.ToColumn))
                     .OrderBy(x => x.Global);

            if (namedRanges.Any())
            {
                return namedRanges.FirstOrDefault().RangeName;
            }
            else
            {
                return null;
            }
        }

        public CellRange GetOrdinal(string name)
        {
            var searchRange = NamedRanges.Where(x => x.RangeName == name);
            if (searchRange.Any()) 
            {
                var temp = searchRange.FirstOrDefault();
                return new CellRange(temp.FromColumn, temp.FromRow, temp.ToColumn.Value, temp.ToRow.Value);
            }
            else 
            {
                return null;
            }
        }

```

**Comment by appel1** [comment] 2024-04-18 06:13
Looks like a good addition.

**Comment by appel1** [comment] 2024-04-18 06:19
I think this is a duplicate of #25. If you create a PR reference that issue instead.

**Closed by appel1** 2024-04-18 06:19 UTC
Labels: duplicate, enhancement
