### ISSUE TITLE
Support XLSX document properties

### ISSUE THREAD

**Issue by superware** [ExcelDataReader/ExcelDataReader#596] opened 2022-04-22 18:48 UTC
Especially core properties such as Created, Last Modified, Title etc. (e.g. docProps\core.xml, docProps\app.xml), probably as IDictionary<string, object>.

P.s. great work!

**Comment by appel1** [comment] 2022-12-03 19:47
Duplicate of #308.

**Closed by appel1** 2022-12-03 19:47 UTC
