### ISSUE TITLE
Sheets missing from Dataset

### ISSUE THREAD

**Issue by rajs68** [ExcelDataReader/ExcelDataReader#66] opened 2015-04-27 17:40 UTC
When reading an xlsx file with empty (only headers) sheets the empty sheets are not in the data set. 
Doing the same with an xls file works just fine.

Suggestions on a workaround would be appreciated.

Code snippet:
```c#
  using (stream = File.Open(filename, FileMode.Open, FileAccess.Read))
            {
                if (filename.EndsWith(".xlsx"))
                {
                    //Reading from a OpenXml Excel file (2007 format; *.xlsx)
                    excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    excelReader.IsFirstRowAsColumnNames = true;
                }
                else //.xls
                {
                    //Reading from a binary Excel file ('97-2003 format; *.xls)
                    excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
                    excelReader.IsFirstRowAsColumnNames = true;
                }
                
                excelDataSet = excelReader.AsDataSet();

                foreach (DataTable table in excelDataSet.Tables)
                {
                    WriteTableToCsvFile(table, path, prefix);
                }
            }
```

**Comment by fwd079** [comment] 2015-05-18 12:06
Reproduced.
The empty sheet does not show if IsFirstRowAsColumnNames is set to true. If you get DataSet without setting IsFirstRowAsColumnNames value, the empty sheet shows. 
Subscribing here, as this is important to one task I am doing currently.

**Comment by Ian1971** [comment] 2015-05-18 12:15
I don't have time to fix but error is probably in
ExcelDataReader.Portable.ExcelOpenXmlReader.LoadDataSetAsync
It looks like if there is now row it continues to next sheet, so does not
call EndLoadTable

If you are in master branch then will be in the equivalent code in that
branch (not portable)

On Mon, May 18, 2015 at 1:06 PM, fwd079 <notifications@github.com> wrote:

> Reproduced.
> The empty sheet does not show if IsFirstRowAsColumnNames is set to true.
> If you get DataSet without setting IsFirstRowAsColumnNames value, the empty
> sheet shows.
> Subscribing here, as this is important to one task I am doing currently.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/66#issuecomment-103039047>
> .
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by fwd079** [comment] 2015-05-18 13:17
I'm just a dll user :) 
But okay will look into how to fork-out stuff and check back in.
Cheers.

**Comment by andez2000** [comment] 2016-05-17 12:02
Problem is in ExcelOpenXmlReader.cs.  Line 401:

if (table.Rows.Count > 0)
	dataset.Tables.Add(table);

**Comment by wizardgsz** [comment] 2016-05-17 12:16
Yeah, we're discussing the same implementation in recent ticket.
By design, the Library "skip" empty sheets.

**Closed** 2016-07-20 08:02 UTC
