### ISSUE TITLE
inconsistent exceptions

### ISSUE THREAD

**Issue by Seabizkit** [ExcelDataReader/ExcelDataReader#326] opened 2018-03-22 19:12 UTC
Hi I seem to be getting different exceptions and inconsistent behavior

This is with the latest: 3.4.0
Reading: .xlsx file

I am using the ExcelDataReader in a MVC website.
Controller - > New instance of Service class -> new instance of LookupSpec Class

I am trying to give context so that the issue is better understood.
**as I only seem to  be getting these issues with the deployed code.**

**_Update_**

> There seems to be a difference with DEBUG VS RELEASE with  AsDataSet(); please investigate the difference

AsDataSet works100% in debug 
but is extremely iffy in RELEASE with the excel file provided

I have wrappers and interfaces for the process.
but **basically i am getting different exceptions, a am using the same file all the time.**
The file has some weird  data but should not be the reason.

Exceptions..
Like: Can not access a closed Stream

> at System.IO.Compression.DeflateStream.EnsureNotDisposed() System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)  
>  at System.Xml.XmlTextReaderImpl.ReadData()  
>  at System.Xml.XmlTextReaderImpl.ParseEndElement()  
>  at System.Xml.XmlTextReaderImpl.ParseElementContent()  
>  at System.Xml.XmlTextReaderImpl.Read()  
>  at System.Xml.XmlReader.FinishReadElementContentAsXxx()  
>  at System.Xml.XmlReader.ReadElementContentAsString()  
>  at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.ReadCell(XmlReader xmlReader, Int32 nextColumnIndex)  
>  at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.ReadRow(XmlReader xmlReader, Int32 nextRowIndex)  
>  at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__87.MoveNext()  
>  at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__85.MoveNext()  
>  at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__84.MoveNext()  
>  at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__81.MoveNext()  
>  at ExcelDataReader.ExcelDataReader`2.Read()  
>  at ExcelDataReader.ExcelDataReaderExtensions.AsDataTable(IExcelDataReader self, ExcelDataTableConfiguration configuration)  
>  at ExcelDataReader.ExcelDataReaderExtensions.AsDataSet(IExcelDataReader self, ExcelDataSetConfiguration configuration)  
>  at Paradox.ExcelDataReader.ExcelDataReaderWrapper.ReadExcelFileSheet(String sheetName) in C:\Projects\Paradox.Importer\Paradox.ExcelReader\ExcelDataReaderWrapper.cs:line 105  

Like: No data exists for the row/column.

> at ExcelDataReader.ExcelDataReader`2.GetValue(Int32 i) ExcelDataReader.ExcelDataReaderExtensions.AsDataTable(IExcelDataReader self, ExcelDataTableConfiguration configuration)  
>  at ExcelDataReader.ExcelDataReaderExtensions.AsDataSet(IExcelDataReader self, ExcelDataSetConfiguration configuration)  
>  at Paradox.ExcelDataReader.ExcelDataReaderWrapper.ReadExcelFileSheet(String sheetName) in C:\Projects\Paradox.Importer\Paradox.ExcelReader\ExcelDataReaderWrapper.cs:line 105  

Please assist in figuring out what is going wrong.
sorry for all the extra detail but wanted to insure that its not me, and that there is actually a bug in ExcelDataReader AsDataSet();

```C#
  public class ExcelLookup : BaseLookup, IParadoxLookup
    {
        //private readonly Lookup _lookup;
        private readonly DataSourceExcel _dataSourceExcel;

        public ExcelLookup(Lookup lookup, DataSourceExcel dataSourceExcel)
        {
            this.LookupName = lookup.LookupName;
            this.KeyColumnIds = lookup.KeyColumnIds;
            this.ValueColumnId = lookup.ValueColumnId;

            //_lookup = lookup;
            _dataSourceExcel = dataSourceExcel;
        }

        public string DataSourceName()
        {
            return _dataSourceExcel.DataSourceName;
        }

        public DataTable GetDataTable()
        {
            if (this.DataTableSource == null)
            {
                //DataTable dataTable = new DataTable();
                try
                {
                    var excelReaderService = new ExcelReaderService(_dataSourceExcel.FileBytes, _dataSourceExcel.OrgnalFileName);
                    var dataTable = excelReaderService.ReadExcelFileSheet(_dataSourceExcel.SheetName);
                    this.DataTableSource = dataTable;
                }
                catch (Exception ex)
                {
                    this.Errors.Add(new LookupErrorDto() { ErrorMessage = ex.Message });
                    throw;
                }
            }
            
            return this.DataTableSource;
        }

        //public EnumDataSourceType GetDatSourceType()
        //{
        //    return (EnumDataSourceType)this._lookup.DataSourceTypeId;
        //}
       
    }
```

```C#
public class LookupSpec
    {
        private readonly ParadoxContext _paradoxContext;

        public IParadoxLookup Ilookup;
        public readonly Lookup Lookup;

        public LookupSpec(Lookup lookup)
        {
            _paradoxContext = new ParadoxContext();
            Lookup = lookup;
            DetermineLookupType(lookup.DataSourceTypeId);
        }

        public List<LookupErrorDto> Errors {
            get { return Ilookup.Errors; }
        }

        public string GetDataSourceName()
        {
            return Ilookup.DataSourceName();
        }

        //public EnumDataSourceType DataSourceType()
        //{
        //    return Ilookup.GetDatSourceType();
        //}

        public DataTable GetDataTable()
        {
            return Ilookup.GetDataTable();
        }

        public void PopulateDic()
        {
            Ilookup.PopulateDictionary();
        }

        private void DetermineLookupType(int dataSourceTypeId)
        {
            switch (dataSourceTypeId)
            {
                case (int)(EnumDataSourceType.Excel):
                    var excelDatasource = _paradoxContext.DataSourceExcels.SingleOrDefault(x => x.Id == Lookup.DataSourceId);
                    ExcelLookup excelLookup = new ExcelLookup(Lookup, excelDatasource);
                    Ilookup = excelLookup;
                    break;
                case (int)(EnumDataSourceType.MsSql):
                    var msSqlDatasource = _paradoxContext.DataSourceSqls.SingleOrDefault(x => x.Id == Lookup.DataSourceId);
                    MsSqlLookup msSqlLookup = new MsSqlLookup(Lookup, msSqlDatasource);
                    Ilookup = msSqlLookup;
                    break;
                default:
                    //ServiceData.Data.AddData("GetLookupContainers", "This method has not been extended to cater for File Formats of type);
                    break;
            }
            
        }
        public string FindStraight(string[] keys)
        {
            return Ilookup.FindStraight(keys);
        }

        public string Find(string[] keys)
        {
            return Ilookup.Find(keys);
        }
    }
```

```C#
public class ExcelDataReaderWrapper : IParadoxExcelReader
{
        
        private IExcelDataReader _reader;
       // private FileStream _stream;

        public ExcelDataReaderWrapper()
        {
            //SetConnection(filePath);
        }

        private bool _disposed = false;
        public virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    if (_reader != null)
                    {
                        _reader.Dispose();
                    }
                    //if (_stream != null)
                    //{
                    //    _stream.Dispose();
                    //}

                }
            }
            _disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~ExcelDataReaderWrapper()
        {
            Dispose();
        }

        public void SetStream(Stream stream)
        {
            _reader = ExcelReaderFactory.CreateReader(stream);
        }

        public DataTable ReadExcelFileSheet(string sheetName)
        {
            //doesnt read all the sheets as a publc property.
            DataSet result = _reader.AsDataSet();
            IEnumerable<DataTable> dataTables = result.Tables.Cast<DataTable>();
            var dataTable = dataTables.SingleOrDefault(x => x.TableName == sheetName);
            if (dataTable == null)
            {
                throw new Exception(string.Format("The sheet({0}) could not be found", sheetName));
            }
            return dataTable;
        }
 }
```
include file - the file has non sense! data that is not the point.
[file test.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/1838946/file.test.xlsx)

**Comment by andersnm** [comment] 2018-03-22 22:37
Hi,

Can we see the (relevant parts of the) `ExcelReaderService` class too? It might be useful to see the full stack trace including the calls through the methods on LookupSpec and ExcelLookup too. I don't see any obvious mistakes in the pasted code, although can't follow all the steps

Some thoughts, 
The attached file.test.xlsx opens without issues in both debug and release builds of the TestApp winforms app in the repo.

Both pasted exceptions pasted indicate the reader has been disposed prematurely. I guess the GC behaves more aggressively in Release than Debug builds, and different exceptions are being generated depending on the timing.

**Comment by Seabizkit** [comment] 2018-03-23 07:18
Hi

included ExcelReaderService class

Also included full stack traces for the exceptions
I agree that it seems like something to do with release being more aggressive, as i think my code is fine.

In release it on `.AsDataSet();` where it seems to hang.

```c#
public class ExcelReaderService : IDisposable
    {
        private IParadoxExcelReader _excelReader;

        //must exist already physically on disk.. full path
        //ToDo: extend to take the bytes and then determin in the reader if it supports file streams.
        public ExcelReaderService(string filePath, EnumExcelReader excelReader = EnumExcelReader.ExcelDataReader)
        {
            SetReader(excelReader);
            _excelReader.SetConnection(filePath);
        }

        //todo: change so the the file read is close within the manager...
        public ExcelReaderService(byte[] fileBytes, string filename,
            EnumExcelReader excelReader = EnumExcelReader.ExcelDataReader)
        {
            SetReader(excelReader);
            if (_excelReader.IsStreamSupported())
            {
                Stream stream = new MemoryStream(fileBytes);
                _excelReader.SetStream(stream);
            }
            else
            {
                //the file name is need for the extention
                var tempFile = FileService.SaveFileToTemp(fileBytes, filename);

                _excelReader.SetConnection(tempFile);
            }
        }

        private void SetReader(EnumExcelReader excelReader)
        {
            switch (excelReader)
            {
                case EnumExcelReader.OleDb:
                    _excelReader = new OleDbWrapper();
                    break;
                case EnumExcelReader.ExcelDataReader:
                    _excelReader = new ExcelDataReaderWrapper();
                    break;
                case EnumExcelReader.InteropExcel:
                    _excelReader = new ExcelReaderInteropService();
                    break;
            }
        }

        public List<string> GetSheetNames()
        {
            return _excelReader.GetSheetNames();
        }

        public DataTable ReadExcelFileSheet(string sheetName)
        {
            return _excelReader.ReadExcelFileSheet(sheetName);
        }

        public string GetSheetNameAtIndex(int index)
        {
            return _excelReader.GetSheetNameAtIndex(index);

        }

        public void Dispose()
        {
            _excelReader.Dispose();
        }
    }
```
ill include the full stacktraces...

exception: Object reference not set to an instance of an object.

```C#
at ExcelDataReader.ExcelDataReader`2.ReadCurrentRow() ExcelDataReader.ExcelDataReader`2.Read()  
 at ExcelDataReader.ExcelDataReaderExtensions.AsDataTable(IExcelDataReader self, ExcelDataTableConfiguration configuration)  
 at ExcelDataReader.ExcelDataReaderExtensions.AsDataSet(IExcelDataReader self, ExcelDataSetConfiguration configuration)  
 at Paradox.ExcelDataReader.ExcelDataReaderWrapper.ReadExcelFileSheet(String sheetName) in C:\Projects\Paradox.Importer\Paradox.ExcelReader\ExcelDataReaderWrapper.cs:line 105  
 at Paradox.DataSourceLookup.ExcelLookup.GetDataTable() in C:\Projects\Paradox.Importer\Paradox.DataSourceLookup\ExcelLookup.cs:line 45  
 at Paradox.DataSourceLookup.LookupSpec.GetDataTable() in C:\Projects\Paradox.Importer\Paradox.DataSourceLookup\LookupSpec.cs:line 40  
 at Paradox.Web.Controllers.LookupController.ConfigureKey(Int32 id) in C:\Projects\Paradox.Importer\Paradox.Web\Controllers\LookupController.cs:line 283  
 at lambda_method(Closure , ControllerBase , Object[] )  
 at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)  
 at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)  
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.b__3d()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.b__32(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.b__1c()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.b__1e(IAsyncResult asyncResult)
```

Excpetion: Can not access a closed Stream.
```C#
at System.IO.Compression.DeflateStream.EnsureNotDisposed() System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)  
 at System.Xml.XmlTextReaderImpl.ReadData()  
 at System.Xml.XmlTextReaderImpl.ParseEndElement()  
 at System.Xml.XmlTextReaderImpl.ParseElementContent()  
 at System.Xml.XmlTextReaderImpl.Read()  
 at System.Xml.XmlReader.FinishReadElementContentAsXxx()  
 at System.Xml.XmlReader.ReadElementContentAsString()  
 at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.ReadCell(XmlReader xmlReader, Int32 nextColumnIndex)  
 at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.ReadRow(XmlReader xmlReader, Int32 nextRowIndex)  
 at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__87.MoveNext()  
 at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__85.MoveNext()  
 at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__84.MoveNext()  
 at ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet.d__81.MoveNext()  
 at ExcelDataReader.ExcelDataReader`2.Read()  
 at ExcelDataReader.ExcelDataReaderExtensions.AsDataTable(IExcelDataReader self, ExcelDataTableConfiguration configuration)  
 at ExcelDataReader.ExcelDataReaderExtensions.AsDataSet(IExcelDataReader self, ExcelDataSetConfiguration configuration)  
 at Paradox.ExcelDataReader.ExcelDataReaderWrapper.ReadExcelFileSheet(String sheetName) in C:\Projects\Paradox.Importer\Paradox.ExcelReader\ExcelDataReaderWrapper.cs:line 105  
 at Paradox.DataSourceLookup.ExcelLookup.GetDataTable() in C:\Projects\Paradox.Importer\Paradox.DataSourceLookup\ExcelLookup.cs:line 45  
 at Paradox.DataSourceLookup.LookupSpec.GetDataTable() in C:\Projects\Paradox.Importer\Paradox.DataSourceLookup\LookupSpec.cs:line 40  
 at Paradox.Web.Controllers.LookupController.ConfigureKey(Int32 id) in C:\Projects\Paradox.Importer\Paradox.Web\Controllers\LookupController.cs:line 283  
 at lambda_method(Closure , ControllerBase , Object[] )  
 at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)  
 at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)  
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.b__3d()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.b__32(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.b__1c()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.b__1e(IAsyncResult asyncResult)
```

exception : No data exists for the row/column.
```c#
at ExcelDataReader.ExcelDataReader`2.GetValue(Int32 i) ExcelDataReader.ExcelDataReaderExtensions.AsDataTable(IExcelDataReader self, ExcelDataTableConfiguration configuration)  
 at ExcelDataReader.ExcelDataReaderExtensions.AsDataSet(IExcelDataReader self, ExcelDataSetConfiguration configuration)  
 at Paradox.ExcelDataReader.ExcelDataReaderWrapper.ReadExcelFileSheet(String sheetName) in C:\Projects\Paradox.Importer\Paradox.ExcelReader\ExcelDataReaderWrapper.cs:line 105  
 at Paradox.DataSourceLookup.ExcelLookup.GetDataTable() in C:\Projects\Paradox.Importer\Paradox.DataSourceLookup\ExcelLookup.cs:line 45  
 at Paradox.DataSourceLookup.LookupSpec.GetDataTable() in C:\Projects\Paradox.Importer\Paradox.DataSourceLookup\LookupSpec.cs:line 40  
 at Paradox.Web.Controllers.LookupController.ConfigureKey(Int32 id) in C:\Projects\Paradox.Importer\Paradox.Web\Controllers\LookupController.cs:line 283  
 at lambda_method(Closure , ControllerBase , Object[] )  
 at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)  
 at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)  
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.b__3d()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.b__32(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.b__1c()  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.b__1e(IAsyncResult asyncResult)
```

**Comment by andersnm** [comment] 2018-03-23 09:35
Thanks, have reduced and reproduced in a console app (tested .NET 2.0, 4.5 and 4.7)

```c#
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;

namespace ExcelProblem
{
    public class ExcelDataReaderWrapper
    {
        private IExcelDataReader _reader;

        private bool _disposed = false;
        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    if (_reader != null)
                    {
                        _reader.Dispose();
                    }
                }
            }
            _disposed = true;
        }

        public void Dispose()
        {
            Console.WriteLine("ExcelDataReaderWrapper.Dispose");
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~ExcelDataReaderWrapper()
        {
            Console.WriteLine("ExcelDataReaderWrapper.Destructor");
            Dispose();
        }

        public DataTable ReadExcelFileSheet(Stream stream, string sheetName)
        {
            _reader = ExcelReaderFactory.CreateReader(stream);

            Console.WriteLine("Calling AsDataSet()");
            DataSet result = _reader.AsDataSet();
            Console.WriteLine("AsDataSet done");

            IEnumerable<DataTable> dataTables = result.Tables.Cast<DataTable>();
            var dataTable = dataTables.SingleOrDefault(x => x.TableName == sheetName);
            if (dataTable == null)
            {
                throw new Exception(string.Format("The sheet({0}) could not be found", sheetName));
            }
            return dataTable;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var bytes = File.ReadAllBytes("..\\..\\file.test.xlsx");
            var wrap = new ExcelDataReaderWrapper();
            var stream = new MemoryStream(bytes);
            var table = wrap.ReadExcelFileSheet(stream, "Sheet1");
            Console.WriteLine("Main done");
        }
    }
}
```

The above code usually hangs, producing output like:

```
Calling AsDataSet()
ExcelDataReaderWrapper.Destructor
ExcelDataReaderWrapper.Dispose
```

But sometimes generates different exceptions from deep within the parser (NREs, different XmlExceptions). 

To resolve, suggest to remove the `~ExcelDataReaderWrapper()` destructor, and instead put the section with `new ExcelReaderService(...)` inside a `using` block. This should free the wrapper (and reader) via the service in a cleaner way at a more appropriate time. 

The code has some issues where ExcelReaderService implements IDisposable, but is not disposed explicitly, and ExcelDataReaderWrapper does not implement IDisposable, but is finalized implicitly too early for some reason: I don't know why the GC elects to invoke the ~ExcelDataReaderWrapper() destructor while ExcelDataReaderWrapper.ReadExcelFileSheet() is being executed and the class instance is rooted in Main. Have to read up on the GC internals to provide an explanation for this, I'm sure there is one :)

**Comment by andersnm** [comment] 2018-03-23 10:58
Here's a shorter repro without any dependencies:

```c#
using System;

namespace FinalizerTest
{
    public class Wrapper {
        ~Wrapper() {
            Console.WriteLine("Destructor");
        }

        public void AllocateManyObjects() {
            Console.WriteLine("Allocating many objects");
            for (var i = 0; i < 1000000; i++) {
                var x = new int[4];
            }
            Console.WriteLine("Allocating many objects done");
        }
    }

    class Program {
        static void Main(string[] args) {
            var wrap = new Wrapper();
            wrap.AllocateManyObjects();
            Console.WriteLine("Main done");
        }
    }
}
```

Output (from release build):
```
Allocating many objects
Destructor
Allocating many objects done
Main done
```

In debug builds the destructor comes last.

Per this article, https://msdn.microsoft.com/en-us/library/ms973837.aspx#dotnetgcbasics_topic5

"a finalizer can be present in any class—it's an optional member that the garbage collector promises to call on otherwise dead objects before it reclaims the memory for that object"

In my opinion the wrapper object is not dead: its on the stack and is executing code. To get to the bottom of this I'll have to dig even deeper, but I think it's better to just remove the destructor. Destructors are typically used to free unmanaged resources, and in this case there are none.

**Comment by andersnm** [comment] 2018-03-23 11:20
This blag post dives deeply into finalizer details, and the last point seems to discuss what we're seeing here:

https://ericlippert.com/2015/05/21/when-everything-you-know-is-wrong-part-two/

 "... a finalizer can run earlier than you think."

Aptly named article too =)

**Comment by Seabizkit** [comment] 2018-03-23 19:10
Thank you so much i will, re-jig my code to consider the things you have said here, thanks for taking the time!!!! to help me out

**Comment by Seabizkit** [comment] 2018-03-24 06:48
i think i found the mistake, 

```C#
 ~ExcelDataReaderWrapper()
        {
            Console.WriteLine("ExcelDataReaderWrapper.Destructor");
            Dispose();
        }
````
should be - now it works in release, or appears to ;-)

```C#
 ~ExcelDataReaderWrapper()
        {
            Console.WriteLine("ExcelDataReaderWrapper.Destructor");
            Dispose(false);
        }
````
but regardless of this, if i take it out im confused as to where i should or shouldnt be disposing stuff.

e.g. MS says

```C#
public virtual void Dispose(bool disposing)
        {
            if (_disposed)
             return;

            if (disposing)
            {
                // Free any other managed objects here.
            }

            // Free any unmanaged objects here.

            _disposed = true;
        }
```
i though this was considered unmanaged code and there for should not be in the disposing block

**Comment by andersnm** [comment] 2018-03-24 09:19
Ah yes, assuming the IParadoxExcelReader interface inherits from IDisposable, then calling Dispose(false) in ~ExcelDataReaderWrapper matches MS' recommended pattern for implementing IDisposable. In comparison, we have two destructors in the ExcelDataReader codebase and both call Dispose(false) only.

Additionally, you should add a call to ExcelReaderService.Dispose() explicitly (or implicitly via `using`).

Without the call to ExcelReaderService.Dispose(), the program relies on the GC to clean up via the destructor at its own discretion. For various reasons it determines the ExcelReaderService object hierarchy is dead immediately after calling into "_reader.AsDataSet()" from the wrapper. Because after that point the program does not touch any class members in the hierarchy directly. This is where it gets hard to reason about.

If you put in the call to ExcelReaderService.Dispose(), the compiler/GC understands to keep the ExcelReaderService object hierarchy alive at least until then.

Updated ExcelLookup.GetDataTable():

```c#
        public DataTable GetDataTable()
        {
            if (this.DataTableSource == null)
            {
                try
                {
                    using (var excelReaderService = new ExcelReaderService(_dataSourceExcel.FileBytes, _dataSourceExcel.OrgnalFileName))
                    {
                        var dataTable = excelReaderService.ReadExcelFileSheet(_dataSourceExcel.SheetName);
                        this.DataTableSource = dataTable;
                    }
                }
                catch (Exception ex)
                {
                    this.Errors.Add(new LookupErrorDto() { ErrorMessage = ex.Message });
                    throw;
                }
            }
            
            return this.DataTableSource;
        }
```

**Comment by Seabizkit** [comment] 2018-03-24 10:24
great minds think a like, just did the above.  and removed the Finalize from  ExcelDataReaderWrapper.

as now i cant tell if it should or shouldnt be there now.

with regards to....
```c#
_reader.Dispose();
```
is this a managed or unmanaged, as my understanding is that its unmanaged and that is why we need to handle the dispose. to that end then shouldn't it be

```c#
public virtual void Dispose(bool disposing)
        {
            if (_disposed)
             return;

            if (disposing)
            {
                // Free any other managed objects here.
            }

            // Free any unmanaged objects here.
            _reader.Dispose();

            _disposed = true;
        }
```
rather than 

```C#
public virtual void Dispose(bool disposing)
        {
            if (_disposed)
             return;

            if (disposing)
            {
                // Free any other managed objects here.
                _reader.Dispose();
            }

            // Free any unmanaged objects here.
            

            _disposed = true;
        }
```
Thanks!

**Comment by andersnm** [comment] 2018-03-24 11:37
It depends on the type of stream being passed to the reader. In this case it's using a MemoryStream, so the whole process is entirely managed. Thus strictly there's no need to call Dispose() on the reader at all, since the GC can figure out itself when to free everything. But it's generally a good practise anyhow.

As far as I understand, the purpose of the IDisposable pattern w/destructor is meant as a last resort for library authors when callers forget to call Dispose(), so things like OS handles will be released. But since this is a closed system where you are both the implementer and caller of Dispose(), you can be 100% certain that Dispose() is indeed called. And whether the stream uses unmanaged resources isn't relevant anymore.

If you know for sure nobody else will use these classes, you could theoretically implement IDisposable in ExcelReaderWrapper simply as (without finalizer, flags and bool overload):

```c#
public void Dispose() 
{
   _reader?.Dispose();
   _reader = null;
}
```

**Closed** 2018-03-27 14:21 UTC
