### ISSUE TITLE
Getting decimal value from cells

### ISSUE THREAD

**Issue by sicknote** [ExcelDataReader/ExcelDataReader#468] opened 2020-04-01 12:08 UTC
Am attempting to load a number from a basic XLS file into a decimal. No matter what number format is used in the Excel file cell, the value comes out as a double. Some of the times, the value comes out correctly and can be converted, but as it's a floating point I sometimes get floating point issues.

ExcelDataReader has the method GetDecimal, inherited from IDataRecord. That suggests it should be possible. However, within XlsxWorksheet, the only place that seems to set the Cell Value is the result of calls to ConvertCellValue. That method does not appear to ever return decimals. Am I reading that correctly?

Is there anyway to avoid issues caused by returning doubles? I would really like to avoid having to perform rounding on the data being read.

**Comment by andersnm** [comment] 2020-04-01 12:36
Hi!

Are you reading XLS or XLSX?

In XLS files, numeric values are physically stored as doubles, and ExcelDataReader returns exactly the same binary value that Excel uses internally. (this is true in ExcelDataReader 3.0 and newer, earlier versions converted to string and back - make sure you are using a recent version!)

In XLSX, numeric values are serialized as strings in XML, and I was pretty sure Excel uses doubles internally and thus the value could be "safely" deserialized back into a double as well. But I'm only guessing here. One could make an argument to parse numeric values in XLSX into decimal instead for improved precision, although would be a breaking change. A small todo is checking the OpenXml spec which XSD type is specified for numeric values, this would typically correlate to a .NET type.

(IDataRecord is loosely based on what you might expect to get back from a general database store, and does not indicate any particular features of the Excel file format.)

**Comment by jrigsby** [comment] 2020-06-24 18:16
I have the same issue. I have a column with three values


41083.27
94416.60
37599.20

Looking at it in Excel I see this number both in the input box and the cell itself. If I increase decimal places shown I do not see anything unexpected as detailed below.

When I read them in using AsDataSet or more directly I get 
41083.270000000004
94416.60
37599.200000000004

If I take the file and save as csv, I get the numbers I expect without additional decimal places.

It turns out that this file came from a third party. If I open it, go to each cell, add a 0 and then backspace it out (thus made no real change) and save the file (simply saving the file isnt enough) it fixes the issue. Numbers come in as expected. If I only do it to one cell, it only fixes that one cell.  The original file had this issue and a test file which was a cut down of that original file with only the bad rows in it also had the issue. 

I can't very well tell clients to do that whenever there is an issue in the validation of my reading of the data. So to "fix" it I read the formatted value of the cell. While not perfect, because there is the chance the format for the cell removes decimal places the person wants us to read in, we can justify this position better than telling the client to fix the data corruption, corruption they cannot readily see in Excel.

Ive attached a zip file. The issue is in the Gross Salary column. saveasnochanges.xsl shows the problem in the first and third rows. oncecell.xsl shows the third row fixed by as I stated, putting a 0 in the cell data and then backspacing it out again, (therefore making no real changes) and saving.

[Temp.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/4827179/Temp.zip)

**Comment by appel1** [comment] 2020-06-24 20:12
@jrigsby 

From a quick test, it looks like Excel always truncates numbers to 15 digits. So if you enter a number like 123456789123456789 it gets changed to 123456789123456000, or 1.23456789123456789 gets changed to 1.23456789123456 even though they can be represented as a 64 bit floating-point value just fine, which is what Excel uses internally to store numbers as @andersnm wrote above. This seems to be done both before a value is formatted to be shown and when a cell edit is committed. The tool that created the attached file probably just saved the value as is from however it calculated it. 

Would be a big change and we'd have to be careful to get the behavior correct in all cases if we decide to attempt to emulate Excel, and probably make it something you opt-in to. I'm not sure it is worth it at all really.

**Closed** 2022-12-03 16:14 UTC

**Comment by raghusingh** [comment] 2024-01-10 11:51
> I have the same issue, or at least potentially as I thought it was a floating point issue hence Im adding it to this report. If it should be its own I apologize. I have a column with three values
> 
> 41083.27 94416.60 37599.20
> 
> Looking at it in Excel I see this number both in the input box and the cell itself. If I increase decimal places shown I do not see anything unexpected as detailed below.
> 
> When I read them in using AsDataSet or more directly I get 41083.270000000004 94416.60 37599.200000000004
> 
> If I take the file and save as csv, I get the numbers I expect without additional decimal places. If I save as to Xlsx and use EPPlus to read, I get the same extra decimal places.
> 
> It turns out that this file came from a third party. If I open it, go to each cell, add a 0 and then backspace it out (thus made no real change) and save the file (simply saving the file isnt enough) it fixes the issue. Numbers come in as expected. If I only do it to one cell, it only fixes that one cell. The original file had this issue and a test file which was a cut down of that original file with only the bad rows in it also had the issue.
> 
> I can't very well tell clients to do that whenever there is an issue in the validation of my reading of the data. So to "fix" it I read the formatted value of the cell. While not perfect, because there is the chance the format for the cell removes decimal places the person wants us to read in, we can justify this position better than telling the client to fix the data corruption, corruption they cannot readily see in Excel.
> 
> Ive attached a zip file. The issue is in the Gross Salary column. saveasnochanges.xsl shows the problem in the first and third rows. oncecell.xsl shows the third row fixed by as I stated, putting a 0 in the cell data and then backspacing it out again, (therefore making no real changes) and saving.
> 
> [Temp.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/4827179/Temp.zip)

You are getting these numbers 41083.270000000004 94416.60 37599.200000000004 because EPPlus applying default formatting and it adds numbers at the end.

You can use number formatting like given below where **#** means optional

    ws.Cells[row, col].Style.Numberformat.Format = "##0.##########"; 

Or
    // Find out column index
    int index1 = GetColumnByName(workSheet, "Premium $");
    workSheet.Column(index1).Style.Numberformat.Format = "##0.##########";

    int index = GetColumnByName(workSheet, "Discount $");
    workSheet.Column(index).Style.Numberformat.Format = "##0.##########";

    static int GetColumnByName(ExcelWorksheet ws, string columnName)
    {
        if (ws == null) throw new ArgumentNullException(nameof(ws));
        return ws.Cells["1:1"].First(c => c.Value.ToString() == columnName).Start.Column;
    }
