### ISSUE TITLE
Cannot read XLS file

### ISSUE THREAD

**Issue by Cristian13Leal** [ExcelDataReader/ExcelDataReader#641] opened 2023-07-06 18:54 UTC
When i try to read this file, i received the error "invalid file signature", Can anyone help me? Thanks
[0000023543.xls](https://github.com/ExcelDataReader/ExcelDataReader/files/11971301/0000023543.xls)

**Comment by appel1** [comment] 2023-07-07 08:57
It's in an older XML based format that is not supported by ExcelDataReader. 

Duplicate of #306.

**Closed by appel1** 2023-07-07 08:57 UTC
