### ISSUE TITLE
Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.

### ISSUE THREAD

**Issue by jeetu-gis** [ExcelDataReader/ExcelDataReader#450] opened 2019-12-13 00:31 UTC
at System.IO.Compression.ZipArchive.ReadCentralDirectory()
   at System.IO.Compression.ZipArchive.get_Entries()
   at ExcelDataReader.Core.ZipWorker.FindEntry(String name)
   at ExcelDataReader.Core.ZipWorker.GetWorkbookStream()
   at ExcelDataReader.Core.OpenXmlFormat.XlsxWorkbook.ReadWorkbook()
   at ExcelDataReader.Core.OpenXmlFormat.XlsxWorkbook..ctor(ZipWorker zipWorker)
   at ExcelDataReader.ExcelOpenXmlReader..ctor(Stream stream)
   at ExcelDataReader.ExcelReaderFactory.CreateReader(Stream fileStream, ExcelReaderConfiguration configuration)
   at sBC.cs:line 137

**Comment by andersnm** [comment] 2019-12-13 00:37
Hi,

That's typical for a corrupt or truncated xlsx. Does it open in excel?

Check this: https://stackoverflow.com/a/20960434

Although I agree the error message isn't very helpful.

**Comment by jeetu-gis** [comment] 2019-12-13 00:45
Looks like it is truncated. I will close this once I am sure.

**Comment by markdou812** [comment] 2021-02-11 14:54
I am experiencing this same error, and it occurs when I open a sheet, then make a change to the sheet using Excel and try to reopen the same sheet from the same file location. I'm not keeping the stream open either.

**Comment by simorocksTheBest** [comment] 2022-06-23 12:12
This error, needs to be better formed.
With a poorly handled web API upload request, for example where a compressed file is involved.

You may pick up a ------WebKitFormBoundary header, and footer.
Which will actually cause this error, however as it stands the error and the cause are too disparate from each other.

**Comment by appel1** [comment] 2022-12-04 18:29
@simorocksTheBest What do you mean with "needs to be better formed"? Do you mean something like suggested in #598 to wrap all exceptions in a ExcelReaderException? 

Closing this since the original question has presumable been solved already.

**Closed by appel1** 2022-12-04 18:29 UTC
