### ISSUE TITLE
Incorrect encoding of Cyrillic worksheet names in XLS files

### ISSUE THREAD

**Issue by skosterin88** [ExcelDataReader/ExcelDataReader#170] opened 2016-10-11 18:36 UTC
I have encountered the following problem using the solution. As I open an XLS file with a Cyrillic-named worksheet, I see the worksheet name in the combo box as unreadable symbols. The table itself is shown adequately but the worksheet name is unreadable. As I open an XLSX file with the same content, there is no such problem. I attach the files I used in a ZIP archive here. 

[Test_CyrillicWorksheetName.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/522643/Test_CyrillicWorksheetName.zip)

**Comment by appel1** [comment] 2016-10-12 07:41
Looks like a duplicate of #152. For BIFF8 the codepage shouldn't be used at all, it is always UTF-16LE.

**Comment by andersnm** [comment] 2017-06-05 20:23
Closing as fixed.

**Closed by andersnm** 2017-06-05 20:23 UTC
