### ISSUE TITLE
The behavior of ExcelReaderFactory.CreateBinaryReader with convertOADate set to true

### ISSUE THREAD

**Issue by chandermani** [ExcelDataReader/ExcelDataReader#74] opened 2015-06-15 21:01 UTC
I created a trivial application to read xls (excel 97-2003) file with date columns. Data in these columns are read as double irrespective of whether the flag `convertOADate` is set to true or false.

Is this is bug or standard behavior?

Do i manually have to convert the values to DateTime using `DateTime.FromOADate`

**Comment by Ian1971** [comment] 2015-06-15 21:27
You shouldn't need to separately convert. Also, I know that feature works
in general do there must be something unusual about your case.

**Comment by chandermani** [comment] 2015-06-18 19:11
Thanks for your feedback @lan1971

But i able to reproduce it easily. Can you check the solution project at

https://drive.google.com/file/d/0B59ctf4e17gZRUZkdHVfRWcyenM/view?usp=sharing

It has the complete setup with a excel (xls) file. The values I get are double.

I am using ExcelDataReader 2.1.2.3 on .Net 4.5

**Comment by wizardgsz** [comment] 2015-06-18 21:37
I'm not able to reproduce your issue using the Excel found on Google Drive.

**Comment by wizardgsz** [comment] 2015-06-18 21:53
I'm not able to reproduce your issue using the Excel found on Google Drive.
Here it is a post-processed sheet starting from your file
https://drive.google.com/file/d/0B_AFpcMZ3jEQNzBJZUtFT255Nms/view?usp=sharing

**Comment by chandermani** [comment] 2015-06-19 16:38
Strange i will try again on another machine and get back.

**Comment by proudchild** [comment] 2015-07-01 16:01
I've been experiencing the same problem...
The date doesn't get converted
code:

<code>
IExcelDataReader excelReader;

            if (extension.Contains("xlsx"))
            {
                excelReader = ExcelReaderFactory.CreateOpenXmlReader(fileStream);
            } else
            {
                excelReader = ExcelReaderFactory.CreateBinaryReader(fileStream,false);
            }
            
            DataSet result = excelReader.AsDataSet();
            List<object> ret = new List<object>();
            foreach (DataTable dt in result.Tables)
            {
                foreach (DataRow dr in dt.Rows)
                {
                    try
                    {
                       //dr[0] always double
                        DateTime date = DateTime.ParseExact(dr[0].ToString(), "dd/MM/yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture);
                        double value = 0; double COFINS = 0; double PIS = 0; double CSLL = 0; double IR = 0; double ISSINSSS = 0; double INSS = 0; double LIQ = 0;
                        long Centro = 0;
</code>

**Comment by pwitvoet** [comment] 2015-10-27 13:53
I ran into the same problem, but eventually figured out what's going on. The `AsDataSet()` function calls `AsDataSet(bool convertOADateTime)`, passing `false` for the `convertOADateTime` argument. That function then overwrites the `ConvertOaDate` property (even though it was set to true by `ExcelReaderFactory.CreateBinaryReader(fileStream, true)`), so you end up with a reader that does not convert OLE Automation dates.

`AsDataSet`'s behavior is definitely counter-intuitive in this regard.

**Comment by skyairwater** [comment] 2016-08-03 20:58
The below two lines worked for me. **pwitvoet**, your explanation is so confusing.

var excelReader = Excel.ExcelReaderFactory.CreateBinaryReader(inputStream, true);

var excelDataSet = excelReader.AsDataSet(true);

**Comment by andersnm** [comment] 2017-06-06 18:44
This behavior is fixed in develop: The `convertOADateTime` parameter has been removed from AsDataSet() and instead obeys the reader's setting. Commit a9e65bb48d8e6de2d15af2ee1c2fea43fafd25dd

**Closed by andersnm** 2017-06-06 18:44 UTC

**Comment by JackMstry** [comment] 2017-06-15 08:07
I think this issue is regarding the **DateTime Format**  of your machine.

I am also facing the issue.@chandermani

How can I resolve it.

**Comment by andersnm** [comment] 2017-06-15 15:29
@JackMstry With ExcelDataReader 2.x, use AsDataSet(**true**) to get dates.

With ExcelDataReader 3.0.0-develop00019 use CreateBinaryReader(stream, **true**) to get dates
