### ISSUE TITLE
Parsing result of .xls file is incorrect

### ISSUE THREAD

**Issue by xinfli** [ExcelDataReader/ExcelDataReader#84] opened 2015-09-14 03:00 UTC
I tried to parse an .xls file and got incorrect content, when I save it as .xlsx file, the parsing result is OK.

Below is my test code:

``` csharp
static void Main(string[] args)
{
    const string filePath = @"C:\TestDemo.xlsx";

    var stream = File.Open(filePath, FileMode.Open, FileAccess.Read); 
    var fi = new FileInfo(filePath);
    var excelReader = fi.Extension == ".xlsx"
        ? ExcelReaderFactory.CreateOpenXmlReader(stream)
        : ExcelReaderFactory.CreateBinaryReader(stream);

    excelReader.IsFirstRowAsColumnNames = true;
    var result = excelReader.AsDataSet();

    foreach (DataTable table in result.Tables)
    {
        Console.WriteLine("Sheet name: {0}", table.TableName);

        foreach (DataRow row in table.Rows)
        {
            Console.WriteLine("Column count: {0}", row.ItemArray.Length);
            var colIndex = 0;
            foreach (var cell in row.ItemArray)
            {
                Console.WriteLine("  {0}: {1}", table.Columns[colIndex].ColumnName, cell);
                colIndex ++;
            }
            Console.WriteLine();
        }
    }

    excelReader.Close();
    Console.ReadKey();
}
```

The output should be:

```
Sheet name: Sheet2
Column count: 3
  Date1: 2015-01-01 00:00:00
  Description2: abc
  Amount3: 0

Column count: 3
  Date1: 2015-01-02 00:00:00
  Description2: ade
  Amount3: 1

Column count: 3
  Date1: 2015-01-03 00:00:00
  Description2: abc
  Amount3: 2

Column count: 3
  Date1: 2015-01-04 00:00:00
  Description2: ade
  Amount3: 3

```

But I got output with unreadable charactor for .xls file:

![wrongoutput](https://cloud.githubusercontent.com/assets/1798198/9841215/b181161e-5acf-11e5-82ef-2f2ee0d5e4fc.png)

I could not attach the .xls file here, please let me know if you need it.

Thanks.

**Comment by Ian1971** [comment] 2015-09-14 06:07
Hard to tell what the problem is.  Perhaps some encoding issue or unusual
case in the original xls that is fixed by excel when you save. Did you
create the original?

**Comment by andersnm** [comment] 2017-07-02 10:24
There has been improvements in parsing both dates and strings in the xls parser, so I bet this is fixed. If there is still a problem, we will need an xls to test with. Thanks!

**Closed by andersnm** 2017-07-02 10:24 UTC
