### ISSUE TITLE
Invalid file signature.

### ISSUE THREAD

**Issue by Breave-YY** [ExcelDataReader/ExcelDataReader#595] opened 2022-04-20 10:41 UTC
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                using var stream = new MemoryStream();
                await args.File.OpenReadStream(maxFileSize).CopyToAsync(stream);
                using (var render = ExcelReaderFactory.CreateReader(stream))
                {
                    var result = render.AsDataSet();
                    var rows = result.Tables[0].Rows;                               
                
(https://github.com/ExcelDataReader/ExcelDataReader/files/8520769/2088002631822628-20210623-074277229-.-.xls)
[Uploading 2088002631822628-20210623-074277229-账务组合查询 - 副本.xls…]()

}

**Comment by appel1** [comment] 2022-04-20 11:20
That file format is not yet supported. Duplicate of #306.

**Closed** 2022-08-25 15:15 UTC
