### ISSUE TITLE
Extract text from big documents faster

### ISSUE THREAD

**Issue by THE-KONDRAT** [ExcelDataReader/ExcelDataReader#653] opened 2023-09-01 08:19 UTC
I have an xlsx document one of whose it's sheets has following dimension:
`<dimension ref="A1:WVJ983035"/>`
But actually text is in A1:E24 area.
Reading in cycles (by rows and row cells) of this file takes about 130 seconds which is inappropriate.
Are there any solutions that could help me avoid reading not existing rows?

**Comment by OwnageIsMagic** [comment] 2023-09-03 18:04
Is it duplicate of https://github.com/ExcelDataReader/ExcelDataReader/issues/618 ?

**Comment by THE-KONDRAT** [comment] 2023-09-04 06:16
> Is it duplicate of #618 ?

Yes, looks like.
But [XlsxHelper](https://github.com/ArjunVachhani/XlsxHelper) reads only xlsx, i need read xls, xlsb too.

**Comment by OwnageIsMagic** [comment] 2023-09-05 00:00
I don't think there is possibility to skip unwanted columns without deep api rewrite, but rows are read lazily. The only problem that the current code reads the whole worksheet to compute actual row count and some other aux props. This can be skipped without api change with trivial/moderate refactoring to do it on demand.
here is offending code
https://github.com/ExcelDataReader/ExcelDataReader/blob/2dc4c7ef261192c37e9b33eec7cb7f9f6e6d9851/src/ExcelDataReader/Core/BinaryFormat/XlsWorksheet.cs#L33
https://github.com/ExcelDataReader/ExcelDataReader/blob/2dc4c7ef261192c37e9b33eec7cb7f9f6e6d9851/src/ExcelDataReader/Core/OpenXmlFormat/XlsxWorksheet.cs#L40
https://github.com/ExcelDataReader/ExcelDataReader/blob/2dc4c7ef261192c37e9b33eec7cb7f9f6e6d9851/src/ExcelDataReader/Core/BinaryFormat/XlsWorksheet.cs#L33

**Closed** 2024-04-18 06:15 UTC
Labels: duplicate
