### ISSUE TITLE
Error when read xls file

### ISSUE THREAD

**Issue by yuyongji1987** [ExcelDataReader/ExcelDataReader#248] opened 2017-07-17 04:40 UTC
when use release 3.0.0-develop00086 and 3.0.0, read xls file throw system.invalidoperationexception "The excel file may be corrupt or truncated. We've read past the end of the file.", but ExcelDataReader 3.0.0-develop00019 is ok.
stacktrace :   在 ExcelDataReader.Core.BinaryFormat.XlsDocument.ReadSectorTable(BinaryReader reader, List`1 chain)
   在 ExcelDataReader.Core.BinaryFormat.XlsDocument..ctor(Stream stream)
   在 ExcelDataReader.Core.BinaryFormat.XlsWorkbook.ReadCompoundDocument(Stream stream)
   在 ExcelDataReader.Core.BinaryFormat.XlsWorkbook..ctor(Stream stream, Encoding fallbackEncoding)
   在 ExcelDataReader.ExcelBinaryReader..ctor(Stream stream, ExcelReaderConfiguration configuration)
   在 ExcelDataReader.ExcelReaderFactory.CreateBinaryReader(Stream fileStream, ExcelReaderConfiguration configuration)

**Comment by andersnm** [comment] 2017-07-17 06:12
Thanks for your report. Can you also share an xls so we can reproduce this too?

**Comment by yuyongji1987** [comment] 2017-07-17 06:45
@andersnm I delete some data from the xls, but you can also reproduce the error.
thanks for your reply
[test.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1151738/test.zip)

**Comment by appel1** [comment] 2017-07-17 09:16
Did a quick bisect and it looks like this broke in https://github.com/ExcelDataReader/ExcelDataReader/commit/4605ce83f1aaa58aa0d52979c0a9b2254019823c.

**Comment by andersnm** [comment] 2017-07-17 09:32
Yeah, had an idea it happened around there. Haven't looked too closely yet, but can repro the issue.

Guess it only happens in bigger XLS'es with more than 109 DIF entries. The particular commit 4605ce83f1aaa58aa0d52979c0a9b2254019823c supports only the 109 DIF entries in the header, but the following commit a20fc74a021638a7de86658cd09de8ff0626817d adds code to read the remaining ones outside the header, with a test for it as well

**Comment by andersnm** [comment] 2017-07-17 10:28
According to this: https://msdn.microsoft.com/en-us/library/dd941958.aspx, the "Next DIFAT Sector Location" field is not obeyed by ExcelDataReader.

The test.xls loads after tweaking ReadDifSectorChain() as follows:

```
var difSector = Header.DifFirstSector;
for (var i = 0; i < Header.DifSectorCount; ++i)
{
    var difContent = ReadSectorAsUInt32s(reader, difSector);
    difSectorChain.AddRange(difContent.GetRange(0, difContent.Count - 1));
    difSector = difContent[difContent.Count - 1];
}
```

instead of `var difSector = (uint)(Header.DifFirstSector + i);`

**Comment by andersnm** [comment] 2017-07-17 16:27
It's fixed in develop, but haven't added test data yet. 

The bug looks to trigger with any XLS above ~15 megabytes. The big test file in the repo "GitIssue_184_FATSectors.xls" looks to be just below the threshold to trigger the bug. :(

Each DIFAT entry describes 128 data sectors/entries at 512 bytes. There are 109 DIFAT entries in the header, plus optional DIFAT sectors elsewhere in the file. Each DIFAT sector contains 127 entries plus a link to the next DIFAT sector. There has to be at least one full DIFAT sector for the bug to happen. Thus, ((109 + 127) DIFAT entries *128 data sectors) * 512 bytes ~= 15 megabytes.

**Comment by appel1** [comment] 2017-07-17 17:44
If size is a concern we could always zip the test xls files.

**Comment by tickytacky** [comment] 2017-07-19 12:02
We've encountered the same problem today with a xls file that has 12.286 KB.
When is a new release planned that conains the fix?

**Comment by andersnm** [comment] 2017-07-19 12:33
@tickytacky Hopefully within a week. But if your file is only 12mb, then it could be something else, f.ex a truncated xls, and could still fail. Do you have a chance to verify the latest build and/or share the xls?

There are unofficial Nuget packages on the build server:
https://ci.appveyor.com/project/andersnm/exceldatareader/build/build-101/artifacts

You can download these locally and configure a Nuget.config such that the package manager finds them:
https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

**Comment by wizardgsz** [comment] 2017-07-19 12:41
Well, talking about the file size: sometimes I read XLS files up to 50/60 MB using the Library...

**Comment by tickytacky** [comment] 2017-07-19 13:17
Your build 3.1.0 101 is working for us!
Unfortunately I cannot send you the file because of internal data from our customer. For a workaround we've deleted the data from beginning of the second sheet (so only data in the first sheet) and it works with the current release (3.0.0). 
I've tried to create a test file for you but when I fill the amount of data like in the original file the test file gets only about 1.500 KB. Maybe it has something to do with historic adding/deleting lots of data in the original file other the past years?!?

**Comment by andersnm** [comment] 2017-07-19 13:24
@tickytacky That's great news! No need to send the file then. You are right that must have to do with adding/deleting data over time. The compound document format is a strange beast :)

**Comment by yuyongji1987** [comment] 2017-07-21 06:46
@andersnm build 3.1.0 101 is working well for me. Thanks!

**Closed** 2017-07-21 10:16 UTC

**Comment by valzak74** [comment] 2024-09-20 07:45
Get the same issue with 3.7.0 version. XLS file 7099 kB with 30146 rows of data in a single worksheet

**Comment by andersnm** [comment] 2024-09-20 08:35
@valzak74 Please create a new issue if you can share the XLS file, there's nothing we can do with just a vague report

**Comment by valzak74** [comment] 2024-09-20 10:04
I can create a new issue but can't publish this file (commercial data present). Can i send it personally by email or messager ? When I try to change data inside the file and save it - file change size and become readable. But I need just original file to be able to read via ExcelDataReader. Note that MS Excel or Libre open original xls without any problems
