### ISSUE TITLE
Zero columns detected  reading Excel file

### ISSUE THREAD

**Issue by dan64** [ExcelDataReader/ExcelDataReader#22] opened 2014-09-05 16:11 UTC
I tried to use your library to read a large file. The current version failed to get the current number of columns. To Fix the problem I had to un-comment the following lines:

// source: ExcelOpenXmlReader.cs, line 134
if (_xmlReader.NodeType == XmlNodeType.Element && _xmlReader.LocalName == XlsxWorksheet.N_col)
      cols++;

Even doing so, the class failed to populate the table, to fix the problem I had to change the following lines:

// source: ExcelOpenXmlReader.cs, line 243
if (a_r != null)
      XlsxDimension.XlsxDim(a_r, out col, out row);
else
      col++;

---

With these fixes the library woks fine, consume few memory and is light-years better than EPPLUS that after consuming 2 GB of memoy was unable to read the file (out of memoy exception).

Moreorever I strongly suggest to change the namespace from "Excel" to something like "ExcelReader" because the name is in conflict with the Microsoft Excel Interop Library. I had to do this change to use both on my project.

Thanks!

**Comment by andersnm** [comment] 2017-06-05 19:47
The relevant code for the first suggestion at ExcelOpenXmlReader.cs, line 134:
```
    //removed: Do not use col to work out number of columns as this is really for defining formatting, so may not contain all columns
    //if (_xmlReader.NodeType == XmlNodeType.Element && _xmlReader.LocalName == XlsxWorksheet.N_col)
    //    cols++;
```
According to the existing comment I don't think we can uncomment this, and seems to be backed by the spec: https://msdn.microsoft.com/en-us/library/office/documentformat.openxml.spreadsheet.column(v=office.14).aspx

If uncommented, the cols variable will only count the number of cells with width/height formatting, and take precedence over the column count derived from the "max-referenced-column" (in the cases the spreadsheet lacks a dimension element and must guess from the data). This cannot be correct.

The second suggestion is in the develop branch already, and currently looks as follows (line 470):
```
    aR = _xmlReader.GetAttribute(XlsxWorksheet.AR);

    if (aR != null)
    {
        ReferenceHelper.ParseReference(aR, out col);
    }
    else
    {
        ++col;
    }
```

Suggest to close this for now, because the issue is partially fixed and also old. If the issue persists, we need some test data to reproduce the problem locally.

**Closed by andersnm** 2017-06-05 19:47 UTC
Labels: bug
